// <auto-generated />
namespace FileLoader.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add_RegularExpression : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_RegularExpression));
        
        string IMigrationMetadata.Id
        {
            get { return "201809051043396_Add_RegularExpression"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
